version: '3.3'

services:
  mongo-staging:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /home/advansat/staging/data:/data/db

  api:
    container_name: api
    depends_on:
      - mongo
    build:
      context: ./api
      dockerfile: dockerfile
    image: dup/iena-api
    restart: always
    ports:
      - 3001:3001
